# Generated by Django 6.0.7 on 2026-07-19 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="file_size",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="image",
            name="height",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="image",
            name="width",
            field=models.IntegerField(default=0),
        ),
    ]
